### ISSUE TITLE
[PaperMC 1.21.6] When pasting a yamipa item frame, the client loses connection.

### ISSUE THREAD

**Issue by MusclePr** [josemmo/yamipa#149]
I will narrow down the reproduction environment. For now, I will report it first.

Server log:
```log
[19:05:10] [Server thread/INFO]: Muscle_p がサーバーに参加しました
[19:05:10] [Server thread/INFO]: まっする joined the game
[19:05:10] [Server thread/INFO]: Muscle_p[/172.69.169.212:49530] logged in with entity id 60 at ([world]50.70464287122876, 70.0, 115.76555441509396)
[19:05:14] [Server thread/INFO]: Muscle_p issued server command: /gamemode creative
[19:05:14] [Server thread/INFO]: [Muscle_p: Set own game mode to Creative Mode]
[19:05:18] [Server thread/INFO]: Muscle_p issued server command: /yamipa list
[19:06:06] [Server thread/INFO]: Muscle_p issued server command: /yamipa download "https://pbs.twimg.com/profile_images/1889682618255548417/73QTjaqa_400x400.jpg" suzume
[19:06:15] [Server thread/INFO]: Muscle_p issued server command: /yamipa place suzume 1
[19:06:20] [Server thread/INFO]: Muscle_p lost connection: Disconnected
[19:06:20] [Server thread/INFO]: Muscle_p がサーバーから退出しました
[19:06:20] [Server thread/INFO]: Disconnecting client Muscle_p
[19:06:20] [Server thread/INFO]: まっする left the game
[19:06:30] [Server thread/INFO]: Server empty for 10 seconds, pausing
[19:06:34] [Craft Scheduler Thread - 26 - YamipaPlugin/INFO]: [ImageRenderer] Saved placed fake images to disk
```

Client log:
```log
[19:06:20] [Render thread/ERROR]: Failed to handle packet net.minecraft.class_8042@45d465eb, disconnecting
java.lang.IllegalStateException: Invalid entity data item type for field 8 on entity class_1533['額縁'/536870911, l='ClientLevel', x=64.97, y=70.50, z=118.50]: old=west(class net.minecraft.class_2350), new=1 minecraft:filled_map(class net.minecraft.class_1799)
	at knot/net.minecraft.class_2945.method_12785(class_2945.java:126) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2945.method_12779(class_2945.java:117) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_634.method_11093(class_634.java:647) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2739.method_11808(class_2739.java:54) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2739.method_65081(class_2739.java:12) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_634.method_48294(class_634.java:2385) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8042.method_48329(class_8042.java:19) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8042.method_65081(class_8042.java:7) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:123) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1318) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:947) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.14.jar:?]
[19:06:20] [Render thread/INFO]: Unloading synced configs from server
[19:06:20] [Render thread/INFO]: Stopping worker threads
[19:06:20] [Render thread/WARN]: Client disconnected with reason: ネットワークプロトコルのエラーが発生しました
[19:06:40] [Render thread/INFO]: Stopping!
```

**Comment by MusclePr** [comment]
Client settings:
- Vanilla 1.21.6
- ERROR Message: **Network Protocol Error**
<details>
<summary>Client log</summary>

```log
[21:35:48] [Render thread/INFO]: Connecting to localhost, 25565
[21:35:50] [Render thread/INFO]: [System] [CHAT] Muscle_p joined the game
[21:35:50] [Render thread/INFO]: Loaded 2 advancements
[21:35:50] [Render thread/ERROR]: Failed to handle packet adb@4da9e7c6, disconnecting
java.lang.IllegalStateException: Invalid entity data item type for field 8 on entity cqs['Item Frame'/536870911, l='ClientLevel', x=7.03, y=75.50, z=5.50]: old=east(class jh), new=1 minecraft:filled_map(class dcv)
	at all.a(SourceFile:126) ~[1.21.6.jar:?]
	at all.a(SourceFile:117) ~[1.21.6.jar:?]
	at grk.a(SourceFile:647) ~[1.21.6.jar:?]
	at afz.a(SourceFile:54) ~[1.21.6.jar:?]
	at afz.a(SourceFile:12) ~[1.21.6.jar:?]
	at grk.a(SourceFile:2385) ~[1.21.6.jar:?]
	at adb.a(SourceFile:19) ~[1.21.6.jar:?]
	at adb.a(SourceFile:7) ~[1.21.6.jar:?]
	at zz.a(SourceFile:27) ~[1.21.6.jar:?]
	at bvx.d(SourceFile:164) [1.21.6.jar:?]
	at bwc.d(SourceFile:23) [1.21.6.jar:?]
	at bvx.B(SourceFile:138) [1.21.6.jar:?]
	at bvx.bA(SourceFile:123) [1.21.6.jar:?]
	at fud.c(SourceFile:1318) [1.21.6.jar:?]
	at fud.f(SourceFile:947) [1.21.6.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:265) [1.21.6.jar:?]
[21:35:50] [Render thread/INFO]: Resizing Dynamic Transforms UBO, capacity limit of 2 reached during a single frame. New capacity will be 4.
[21:35:50] [Render thread/INFO]: Resizing Dynamic Transforms UBO, capacity limit of 4 reached during a single frame. New capacity will be 8.
[21:35:50] [Render thread/WARN]: Client disconnected with reason: Network Protocol Error
[21:35:59] [Render thread/INFO]: Stopping!
```
</details>

Server settings:
- PaperMC 1.21.6-44
  - Yamipa 1.3.2
  - ProtocolLib 5.4.0-SNAPSHOT-750
<details>
<summary>Server log</summary>

```log
Starting org.bukkit.craftbukkit.Main
2025-06-26T12:35:06.028231996Z ServerMain WARN Advanced terminal features are not available in this environment
[21:35:06 INFO]: [bootstrap] Running Java 21 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS; Eclipse Adoptium Temurin-21.0.3+9) on Linux 6.6.87.1-microsoft-standard-WSL2 (amd64)
[21:35:06 INFO]: [bootstrap] Loading Paper 1.21.6-44-main@4e1a255 (2025-06-25T20:49:06Z) for Minecraft 1.21.6
[21:35:06 INFO]: [PluginInitializerManager] Initializing plugins...
[21:35:06 INFO]: [PluginRemapper] Remapping plugin 'plugins/YamipaPlugin-1.3.2.jar'...
[21:35:06 INFO]: [PluginRemapper] Done remapping plugin 'plugins/YamipaPlugin-1.3.2.jar' in 286ms.
[21:35:06 INFO]: [PluginInitializerManager] Initialized 2 plugins
[21:35:06 INFO]: [PluginInitializerManager] Bukkit plugins (2):
 - ProtocolLib (5.4.0-SNAPSHOT-750), YamipaPlugin (1.3.2)
[21:35:09 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[21:35:09 INFO]: Loaded 1407 recipes
[21:35:09 INFO]: Loaded 1520 advancements
[21:35:09 INFO]: [ca.spottedleaf.dataconverter.minecraft.datatypes.MCTypeRegistry] Initialising converters for DataConverter...
[21:35:09 INFO]: [ca.spottedleaf.dataconverter.minecraft.datatypes.MCTypeRegistry] Finished initialising converters for DataConverter in 176.3ms
[21:35:10 INFO]: Starting minecraft server version 1.21.6
[21:35:10 INFO]: Loading properties
[21:35:10 INFO]: This server is running Paper version 1.21.6-44-main@4e1a255 (2025-06-25T20:49:06Z) (Implementing API version 1.21.6-R0.1-SNAPSHOT)
[21:35:10 INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
[21:35:10 INFO]: Server Ping Player Sample Count: 12
[21:35:10 INFO]: Using 4 threads for Netty based IO
[21:35:10 INFO]: [MoonriseCommon] Paper is using 8 worker threads, 1 I/O threads
[21:35:10 INFO]: [ChunkTaskScheduler] Chunk system is using population gen parallelism: true
[21:35:10 INFO]: Default game type: SURVIVAL
[21:35:10 INFO]: Generating keypair
[21:35:10 INFO]: Starting Minecraft server on *:25565
[21:35:10 INFO]: Using epoll channel type
[21:35:10 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[21:35:10 INFO]: Paper: Using OpenSSL 3.x.x (Linux x86_64) cipher from Velocity.
[21:35:10 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.4.0-SNAPSHOT-750
[21:35:10 WARN]: [ProtocolLib] Version (MC: 1.21.6) has not yet been tested! Proceed with caution.
[21:35:11 INFO]: [YamipaPlugin] Loading server plugin YamipaPlugin v1.3.2
[21:35:11 INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:35:11 INFO]: [ProtocolLib] Enabling ProtocolLib v5.4.0-SNAPSHOT-750
[21:35:11 INFO]: Preparing level "world"
[21:35:11 INFO]: Preparing start region for dimension minecraft:overworld
[21:35:11 INFO]: Preparing spawn area: 0%
[21:35:11 INFO]: Time elapsed: 426 ms
[21:35:11 INFO]: Preparing start region for dimension minecraft:the_nether
[21:35:11 INFO]: Preparing spawn area: 0%
[21:35:11 INFO]: Time elapsed: 35 ms
[21:35:11 INFO]: Preparing start region for dimension minecraft:the_end
[21:35:11 INFO]: Preparing spawn area: 0%
[21:35:11 INFO]: Time elapsed: 22 ms
[21:35:11 INFO]: [YamipaPlugin] Enabling YamipaPlugin v1.3.2
[21:35:11 INFO]: [YamipaPlugin] Enabled image animation support
[21:35:11 WARN]: [YamipaPlugin] [FileSystemWatcher] Device does not support inotify, detection of file changes will be slower
[21:35:11 INFO]: [spark] Starting background profiler...
[21:35:12 INFO]: Done preparing level "world" (0.956s)
[21:35:12 INFO]: Starting remote control listener
[21:35:12 INFO]: Thread RCON Listener started
[21:35:12 INFO]: RCON running on 0.0.0.0:25575
[21:35:12 INFO]: Running delayed init tasks
[21:35:12 INFO]: Done (6.333s)! For help, type "help"
[Rcon loop] MCServer is listening, running startup
[Rcon loop] running - op Muscle_p
[21:35:18 INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 started
[21:35:18 INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 shutting down
[Rcon loop] Nothing changed. The player already is an operator
[Rcon loop] No addition rcon commands are given, stopping rcon cmd service
[21:35:50 INFO]: UUID of player Muscle_p is b0f19f33-fa11-489f-92ba-35a43418d7ea
[21:35:50 INFO]: Muscle_p joined the game
[21:35:50 INFO]: Muscle_p[/172.18.0.1:58598] logged in with entity id 132 at ([world]8.022832881005325, 75.0, 5.411222977982036)
[21:35:50 INFO]: Muscle_p lost connection: Disconnected
[21:35:50 INFO]: Muscle_p left the game
```
</details>

**Comment by MusclePr** [comment]
## 🛠️ Compatible with 1.21.6: Proposed fix for ItemFrame's EntityMetadataPacket field ID

The DataWatcher/EntityData field ID for ItemFrame may have changed in Minecraft 1.21.6, and if left unchanged, client crashes will occur. 
We have confirmed that the following version split fix will allow it to function properly in 1.21.6.

### Example of correction
```java
    ITEM_INDEX = Internals.MINECRAFT_VERSION < 21.6 ? (Internals.MINECRAFT_VERSION < 17 ? 7 : 8) : 9;
```
### Original
https://github.com/josemmo/yamipa/blob/655cf82b50e060b1cca5c9fc1b92008d3f295135/src/main/java/io/josemmo/bukkit/plugin/packets/EntityMetadataPacket.java#L24

**Comment by wtlgo** [comment]
@MusclePr, maybe if you do a pull request, Jose would notice your fix faster?

**Comment by MusclePr** [comment]
## YamipaPlugin 1.3.2
|✅|Paper|ProtocolLib|Yamipa|
|--|-----|-----------|------|
|NG|1.19.4|5.0.0 (1.19.4)|1.3.2|
|NG|1.19.4|5.1.0 (1.20)|1.3.2|
|NG|1.19.4|5.2.0 (1.20.4)|1.3.2|
|NG|1.19.4|5.3.0 (1.21.1)|1.3.2|
|NG|1.19.4|5.4.0-SNAPSHOT-753 (1.21.3-1.21.6)|1.3.2|

<details>
<summary>YamipaPlugin-1.3.2-SNAPSHOT-b2</summary>

|✅|Paper|ProtocolLib|Yamipa|Error|
|--|-----|-----------|------|----|
|OK|1.19.4|5.0.0 (1.19.4)|1.3.2-SNAPSHOT-b2||
|OK|1.19.4|5.1.0 (1.20)|1.3.2-SNAPSHOT-b2||
|OK|1.19.4|5.2.0 (1.20.4)|1.3.2-SNAPSHOT-b2||
|NG|1.19.4|5.3.0 (1.21.1)|1.3.2-SNAPSHOT-b2|NoClassDefFoundError|
|NG|1.19.4|5.4.0-SNAPSHOT-753 (1.21.3-1.21.6)|1.3.2-SNAPSHOT-b2|NoClassDefFoundError|
</details>

**Comment by josemmo** [comment]
@MusclePr were you able to place and remove images? I wasn't able to render them in those versions, though it didn't crash.

**Comment by MusclePr** [comment]
@josemmo 
Yes, the command succeeded, but the image just didn't display.

**Comment by MusclePr** [comment]
@josemmo 
Hopefully this will now display images in 1.19.4!

|✅|Paper|ProtocolLib|Yamipa|
|--|-----|-----------|------|
|OK|1.19.4|[5.4.0-SNAPSHOT](https://ci.dmulloy2.net/job/ProtocolLib/)-753|1.3.3-SNAPSHOT|
|OK|1.21.8|[5.4.0-SNAPSHOT](https://ci.dmulloy2.net/job/ProtocolLib/)-753|1.3.3-SNAPSHOT|

#153 WrappedDataWatcher may require lazy initialization as of ProtocolLib 5.3.0.

**Comment by MusclePr** [comment]
@josemmo 
I'm checking compatibility on the develop branch and found some issues.

- Sorry, my fix doesn't work in ProtocolLib 5.3.0, but it seems to work in 5.4.0-SNAPSHOT.
- I've confirmed that images don't display in 1.19.1.

**Comment by josemmo** [comment]
Hi @MusclePr,

That's weird, the tests are passing for the lastest commit of develop: https://github.com/josemmo/yamipa/actions/runs/16606328432

If it works with ProtocolLib 5.4.0-SNAPSHOT, then I'd say it's fine.
